version: '2'
services:
  user_service:
    build: .
    ports:
     - "5000:5000"
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/app
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    command: mongod --port 27017
